"""pyOptiGTest test functions - individual function modules."""

from pyOptiGTest.base import TestFunction  # noqa: F401

from .funAHE import FunAHE, funAHE
from .funAMGM import FunAMGM, funAMGM
from .funAckley2 import FunAckley2, funAckley2
from .funAckley3 import FunAckley3, funAckley3
from .funAckley4 import FunAckley4, funAckley4
from .funAdjiman import FunAdjiman, funAdjiman
from .funAlpine1 import FunAlpine1, funAlpine1
from .funAlpine2 import FunAlpine2, funAlpine2
from .funBartelsConn import FunBartelsConn, funBartelsConn
from .funBeale import FunBeale, funBeale
from .funBiggsExp2 import FunBiggsExp2, funBiggsExp2
from .funBiggsExp3 import FunBiggsExp3, funBiggsExp3
from .funBiggsExp4 import FunBiggsExp4, funBiggsExp4
from .funBiggsExp5 import FunBiggsExp5, funBiggsExp5
from .funBiggsExp6 import FunBiggsExp6, funBiggsExp6
from .funBird import FunBird, funBird
from .funBohachevsky1 import FunBohachevsky1, funBohachevsky1
from .funBohachevsky2 import FunBohachevsky2, funBohachevsky2
from .funBohachevsky3 import FunBohachevsky3, funBohachevsky3
from .funBooth import FunBooth, funBooth
from .funBoxBetts import FunBoxBetts, funBoxBetts
from .funBrad import FunBrad, funBrad
from .funBranin1 import FunBranin1, funBranin1
from .funBranin2 import FunBranin2, funBranin2
from .funBrent import FunBrent, funBrent
from .funBrown import FunBrown, funBrown
from .funBukin01 import FunBukin01, funBukin01
from .funBukin02 import FunBukin02, funBukin02
from .funBukin03 import FunBukin03, funBukin03
from .funBukin04 import FunBukin04, funBukin04
from .funBukin05 import FunBukin05, funBukin05
from .funBukin06 import FunBukin06, funBukin06
from .funBukin07 import FunBukin07, funBukin07
from .funBukin08 import FunBukin08, funBukin08
from .funBukin09 import FunBukin09, funBukin09
from .funBukin10 import FunBukin10, funBukin10
from .funBukin11 import FunBukin11, funBukin11
from .funBukin12 import FunBukin12, funBukin12
from .funBukin13 import FunBukin13, funBukin13
from .funBukin14 import FunBukin14, funBukin14
from .funBukin15 import FunBukin15, funBukin15
from .funBukin16 import FunBukin16, funBukin16
from .funBukin17 import FunBukin17, funBukin17
from .funBukin18 import FunBukin18, funBukin18
from .funBukin19 import FunBukin19, funBukin19
from .funBukin20 import FunBukin20, funBukin20
from .funCamelbackSixHump import FunCamelbackSixHump, funCamelbackSixHump
from .funCamelbackThreeHump import FunCamelbackThreeHump, funCamelbackThreeHump
from .funCarromTable import FunCarromTable, funCarromTable
from .funChenBird import FunChenBird, funChenBird
from .funChenV import FunChenV, funChenV
from .funChichinadze import FunChichinadze, funChichinadze
from .funChungReynolds import FunChungReynolds, funChungReynolds
from .funCigar import FunCigar, funCigar
from .funCola import FunCola, funCola
from .funColville import FunColville, funColville
from .funCons1 import FunCons1, funCons1
from .funCons2 import FunCons2, funCons2
from .funConsCTP11 import FunConsCTP11, funConsCTP11
from .funConsCTP12 import FunConsCTP12, funConsCTP12
from .funConsChakongHaimes1 import FunConsChakongHaimes1, funConsChakongHaimes1
from .funConsChakongHaimes2 import FunConsChakongHaimes2, funConsChakongHaimes2
from .funConsConstrEx1 import FunConsConstrEx1, funConsConstrEx1
from .funConsConstrEx2 import FunConsConstrEx2, funConsConstrEx2
from .funConsKornBinh1 import FunConsKornBinh1, funConsKornBinh1
from .funConsKornBinh2 import FunConsKornBinh2, funConsKornBinh2
from .funConsOsyczkaKundu1 import FunConsOsyczkaKundu1, funConsOsyczkaKundu1
from .funConsOsyczkaKundu2 import FunConsOsyczkaKundu2, funConsOsyczkaKundu2
from .funConsOsyczkaKundu3 import FunConsOsyczkaKundu3, funConsOsyczkaKundu3
from .funConsOsyczkaKundu4 import FunConsOsyczkaKundu4, funConsOsyczkaKundu4
from .funConsOsyczkaKundu5 import FunConsOsyczkaKundu5, funConsOsyczkaKundu5
from .funConsOsyczkaKundu6 import FunConsOsyczkaKundu6, funConsOsyczkaKundu6
from .funConsSimionescu import FunConsSimionescu, funConsSimionescu
from .funConsTestFun41 import FunConsTestFun41, funConsTestFun41
from .funConsTestFun42 import FunConsTestFun42, funConsTestFun42
from .funConsTestFun43 import FunConsTestFun43, funConsTestFun43
from .funConsTownsend import FunConsTownsend, funConsTownsend
from .funCorana import FunCorana, funCorana
from .funCosineMixture import FunCosineMixture, funCosineMixture
from .funCrossInTray import FunCrossInTray, funCrossInTray
from .funCrossLegTable import FunCrossLegTable, funCrossLegTable
from .funCrownedCross import FunCrownedCross, funCrownedCross
from .funCsendes import FunCsendes, funCsendes
from .funCst import FunCst, funCst
from .funCube import FunCube, funCube
from .funCustom01 import FunCustom01, funCustom01
from .funCustom02 import FunCustom02, funCustom02
from .funCustom03 import FunCustom03, funCustom03
from .funCustom04 import FunCustom04, funCustom04
from .funCustom05 import FunCustom05, funCustom05
from .funCustom06 import FunCustom06, funCustom06
from .funCustom07 import FunCustom07, funCustom07
from .funDamavandi import FunDamavandi, funDamavandi
from .funDeVilliersGlasser1 import FunDeVilliersGlasser1, funDeVilliersGlasser1
from .funDeVilliersGlasser2 import FunDeVilliersGlasser2, funDeVilliersGlasser2
from .funDeb1 import FunDeb1, funDeb1
from .funDeb2 import FunDeb2, funDeb2
from .funDeb3 import FunDeb3, funDeb3
from .funDeb4 import FunDeb4, funDeb4
from .funDecanomial import FunDecanomial, funDecanomial
from .funDeceptive import FunDeceptive, funDeceptive
from .funDeckkersAarts import FunDeckkersAarts, funDeckkersAarts
from .funDeflectedCorrugatedSpring import FunDeflectedCorrugatedSpring, funDeflectedCorrugatedSpring
from .funDejong import FunDejong, funDejong
from .funDisk2 import FunDisk2, funDisk2
from .funDisk25 import FunDisk25, funDisk25
from .funDixon import FunDixon, funDixon
from .funDixonPrice import FunDixonPrice, funDixonPrice
from .funDolan import FunDolan, funDolan
from .funDropWave import FunDropWave, funDropWave
from .funEX1 import FunEX1, funEX1
from .funEasom import FunEasom, funEasom
from .funEggCrate import FunEggCrate, funEggCrate
from .funEggHolder import FunEggHolder, funEggHolder
from .funElAttarVidyasogarDutta import FunElAttarVidyasogarDutta, funElAttarVidyasogarDutta
from .funExp2 import FunExp2, funExp2
from .funExp3 import FunExp3, funExp3
from .funExp4 import FunExp4, funExp4
from .funExp5 import FunExp5, funExp5
from .funExp6 import FunExp6, funExp6
from .funExponential import FunExponential, funExponential
from .funFreudensteinRoth import FunFreudensteinRoth, funFreudensteinRoth
from .funGear import FunGear, funGear
from .funGiunta import FunGiunta, funGiunta
from .funGoldsteinPrice import FunGoldsteinPrice, funGoldsteinPrice
from .funGriewank import FunGriewank, funGriewank
from .funGulfResearch import FunGulfResearch, funGulfResearch
from .funHansen import FunHansen, funHansen
from .funHartmann3 import FunHartmann3, funHartmann3
from .funHartmann6 import FunHartmann6, funHartmann6
from .funHelicalValley import FunHelicalValley, funHelicalValley
from .funHimmelblau import FunHimmelblau, funHimmelblau
from .funHolzman import FunHolzman, funHolzman
from .funHosaki import FunHosaki, funHosaki
from .funInfiniti import FunInfiniti, funInfiniti
from .funJennrichSampson import FunJennrichSampson, funJennrichSampson
from .funJudge import FunJudge, funJudge
from .funKatsuura import FunKatsuura, funKatsuura
from .funKeane import FunKeane, funKeane
from .funKowalik import FunKowalik, funKowalik
from .funLangermann5 import FunLangermann5, funLangermann5
from .funLangermann52 import FunLangermann52, funLangermann52
from .funLeon import FunLeon, funLeon
from .funLevy03 import FunLevy03, funLevy03
from .funLevy05 import FunLevy05, funLevy05
from .funLevy13 import FunLevy13, funLevy13
from .funMatyas import FunMatyas, funMatyas
from .funMcCormick import FunMcCormick, funMcCormick
from .funMichalewicz import FunMichalewicz, funMichalewicz
from .funMieleCantrell import FunMieleCantrell, funMieleCantrell
from .funMishra01 import FunMishra01, funMishra01
from .funMishra02 import FunMishra02, funMishra02
from .funMishra03 import FunMishra03, funMishra03
from .funMishra04 import FunMishra04, funMishra04
from .funMishra05 import FunMishra05, funMishra05
from .funMishra06 import FunMishra06, funMishra06
from .funMishra07 import FunMishra07, funMishra07
from .funMishra08 import FunMishra08, funMishra08
from .funMishra09 import FunMishra09, funMishra09
from .funMishra10 import FunMishra10, funMishra10
from .funMishra11 import FunMishra11, funMishra11
from .funMystery import FunMystery, funMystery
from .funNeedleEye import FunNeedleEye, funNeedleEye
from .funNewFunction1 import FunNewFunction1, funNewFunction1
from .funNewFunction2 import FunNewFunction2, funNewFunction2
from .funNewFunction3 import FunNewFunction3, funNewFunction3
from .funNull import FunNull, funNull
from .funObjCTP11 import FunObjCTP11, funObjCTP11
from .funObjCTP12 import FunObjCTP12, funObjCTP12
from .funObjChakongHaimes1 import FunObjChakongHaimes1, funObjChakongHaimes1
from .funObjChakongHaimes2 import FunObjChakongHaimes2, funObjChakongHaimes2
from .funObjConstrEx1 import FunObjConstrEx1, funObjConstrEx1
from .funObjConstrEx2 import FunObjConstrEx2, funObjConstrEx2
from .funObjFonsecaFleming1 import FunObjFonsecaFleming1, funObjFonsecaFleming1
from .funObjFonsecaFleming2 import FunObjFonsecaFleming2, funObjFonsecaFleming2
from .funObjKornBinh1 import FunObjKornBinh1, funObjKornBinh1
from .funObjKornBinh2 import FunObjKornBinh2, funObjKornBinh2
from .funObjKursawe1 import FunObjKursawe1, funObjKursawe1
from .funObjKursawe2 import FunObjKursawe2, funObjKursawe2
from .funObjMultiSchaffer11 import FunObjMultiSchaffer11, funObjMultiSchaffer11
from .funObjMultiSchaffer12 import FunObjMultiSchaffer12, funObjMultiSchaffer12
from .funObjMultiSchaffer21 import FunObjMultiSchaffer21, funObjMultiSchaffer21
from .funObjMultiSchaffer22 import FunObjMultiSchaffer22, funObjMultiSchaffer22
from .funObjOsyczkaKundu1 import FunObjOsyczkaKundu1, funObjOsyczkaKundu1
from .funObjOsyczkaKundu2 import FunObjOsyczkaKundu2, funObjOsyczkaKundu2
from .funObjPoloni1 import FunObjPoloni1, funObjPoloni1
from .funObjPoloni2 import FunObjPoloni2, funObjPoloni2
from .funObjTestFun41 import FunObjTestFun41, funObjTestFun41
from .funObjTestFun42 import FunObjTestFun42, funObjTestFun42
from .funObjViennet1 import FunObjViennet1, funObjViennet1
from .funObjViennet2 import FunObjViennet2, funObjViennet2
from .funObjViennet3 import FunObjViennet3, funObjViennet3
from .funObjZDT11 import FunObjZDT11, funObjZDT11
from .funObjZDT12 import FunObjZDT12, funObjZDT12
from .funObjZDT21 import FunObjZDT21, funObjZDT21
from .funObjZDT22 import FunObjZDT22, funObjZDT22
from .funObjZDT31 import FunObjZDT31, funObjZDT31
from .funObjZDT32 import FunObjZDT32, funObjZDT32
from .funObjZDT41 import FunObjZDT41, funObjZDT41
from .funObjZDT42 import FunObjZDT42, funObjZDT42
from .funObjZDT61 import FunObjZDT61, funObjZDT61
from .funObjZDT62 import FunObjZDT62, funObjZDT62
from .funOddSquare import FunOddSquare, funOddSquare
from .funParsopoulos import FunParsopoulos, funParsopoulos
from .funPathological import FunPathological, funPathological
from .funPaviani import FunPaviani, funPaviani
from .funPeaks import FunPeaks, funPeaks
from .funPeaksN import FunPeaksN, funPeaksN
from .funPenHolder import FunPenHolder, funPenHolder
from .funPenalty1 import FunPenalty1, funPenalty1
from .funPenalty2 import FunPenalty2, funPenalty2
from .funPeriodic import FunPeriodic, funPeriodic
from .funPinter import FunPinter, funPinter
from .funPlateau import FunPlateau, funPlateau
from .funPowell import FunPowell, funPowell
from .funPowerSum import FunPowerSum, funPowerSum
from .funPrice01 import FunPrice01, funPrice01
from .funPrice2 import FunPrice2, funPrice2
from .funPrice3 import FunPrice3, funPrice3
from .funPrice4 import FunPrice4, funPrice4
from .funQing import FunQing, funQing
from .funQuadratic import FunQuadratic, funQuadratic
from .funQuartic import FunQuartic, funQuartic
from .funQuintic import FunQuintic, funQuintic
from .funRHE import FunRHE, funRHE
from .funRana import FunRana, funRana
from .funRastrigin import FunRastrigin, funRastrigin
from .funRipple01 import FunRipple01, funRipple01
from .funRipple25 import FunRipple25, funRipple25
from .funRosenbrock import FunRosenbrock, funRosenbrock
from .funRosenbrockM import FunRosenbrockM, funRosenbrockM
from .funRosenbrockMS import FunRosenbrockMS, funRosenbrockMS
from .funRotatedEllipse1 import FunRotatedEllipse1, funRotatedEllipse1
from .funRotatedEllipse2 import FunRotatedEllipse2, funRotatedEllipse2
from .funRump import FunRump, funRump
from .funSalomon import FunSalomon, funSalomon
from .funSargan import FunSargan, funSargan
from .funSchaffer1 import FunSchaffer1, funSchaffer1
from .funSchaffer2 import FunSchaffer2, funSchaffer2
from .funSchaffer3 import FunSchaffer3, funSchaffer3
from .funSchaffer4 import FunSchaffer4, funSchaffer4
from .funSchaffer6 import FunSchaffer6, funSchaffer6
from .funSchmidtVetters import FunSchmidtVetters, funSchmidtVetters
from .funSchwefel01 import FunSchwefel01, funSchwefel01
from .funSchwefel02 import FunSchwefel02, funSchwefel02
from .funSchwefel04 import FunSchwefel04, funSchwefel04
from .funSchwefel06 import FunSchwefel06, funSchwefel06
from .funSchwefel20 import FunSchwefel20, funSchwefel20
from .funSchwefel21 import FunSchwefel21, funSchwefel21
from .funSchwefel22 import FunSchwefel22, funSchwefel22
from .funSchwefel23 import FunSchwefel23, funSchwefel23
from .funSchwefel25 import FunSchwefel25, funSchwefel25
from .funSchwefel26 import FunSchwefel26, funSchwefel26
from .funSchwefel36 import FunSchwefel36, funSchwefel36
from .funShekel05 import FunShekel05, funShekel05
from .funShekel07 import FunShekel07, funShekel07
from .funShekel10 import FunShekel10, funShekel10
from .funShubert1 import FunShubert1, funShubert1
from .funShubert3 import FunShubert3, funShubert3
from .funShubert4 import FunShubert4, funShubert4
from .funSimionescu import FunSimionescu, funSimionescu
from .funSineEnveloppe import FunSineEnveloppe, funSineEnveloppe
from .funSlope import FunSlope, funSlope
from .funSodp import FunSodp, funSodp
from .funSphere import FunSphere, funSphere
from .funStep import FunStep, funStep
from .funStep1 import FunStep1, funStep1
from .funStep2 import FunStep2, funStep2
from .funStep3 import FunStep3, funStep3
from .funStepInt import FunStepInt, funStepInt
from .funStochastic import FunStochastic, funStochastic
from .funStretchedV import FunStretchedV, funStretchedV
from .funStyblinskiTang import FunStyblinskiTang, funStyblinskiTang
from .funSumSquare import FunSumSquare, funSumSquare
from .funTownsend import FunTownsend, funTownsend
from .funTreccani import FunTreccani, funTreccani
from .funTrefethen import FunTrefethen, funTrefethen
from .funTrid import FunTrid, funTrid
from .funTrigonometric1 import FunTrigonometric1, funTrigonometric1
from .funTrigonometric2 import FunTrigonometric2, funTrigonometric2
from .funTrigonometric3 import FunTrigonometric3, funTrigonometric3
from .funTripod import FunTripod, funTripod
from .funTubeHolder import FunTubeHolder, funTubeHolder
from .funUrsem01 import FunUrsem01, funUrsem01
from .funUrsem3 import FunUrsem3, funUrsem3
from .funUrsem4 import FunUrsem4, funUrsem4
from .funUrsemWaves import FunUrsemWaves, funUrsemWaves
from .funVenterSobiezcczanskiSobieski import FunVenterSobiezcczanskiSobieski, funVenterSobiezcczanskiSobieski
from .funVincent import FunVincent, funVincent
from .funWatson import FunWatson, funWatson
from .funWavy import FunWavy, funWavy
from .funWayburnSeader1 import FunWayburnSeader1, funWayburnSeader1
from .funWayburnSeader2 import FunWayburnSeader2, funWayburnSeader2
from .funWeibull import FunWeibull, funWeibull
from .funWeierstrass import FunWeierstrass, funWeierstrass
from .funWhitley import FunWhitley, funWhitley
from .funWolfe import FunWolfe, funWolfe
from .funXinSheYang1 import FunXinSheYang1, funXinSheYang1
from .funXinSheYang2 import FunXinSheYang2, funXinSheYang2
from .funXinSheYang3 import FunXinSheYang3, funXinSheYang3
from .funXinSheYang4 import FunXinSheYang4, funXinSheYang4
from .funXor import FunXor, funXor
from .funYaoLiu4 import FunYaoLiu4, funYaoLiu4
from .funYaoLiu9 import FunYaoLiu9, funYaoLiu9
from .funZacharov import FunZacharov, funZacharov
from .funZeroSum import FunZeroSum, funZeroSum
from .funZettl import FunZettl, funZettl
from .funZimmerman import FunZimmerman, funZimmerman
from .funZirilli import FunZirilli, funZirilli

